import type { BrushPreset, BrushCategory } from '../../types/brush.ts'

export const DEFAULT_PRESETS: BrushPreset[] = [
  // ── Draw ──
  {
    id: 'round-pen',
    name: 'Round Pen',
    category: 'draw',
    size: 12,
    minSize: 5,
    maxSize: 50,
    opacity: 1,
    spacing: 0.1,
    hardness: 1,
    smoothing: 0.5,
    pressureSizeEnabled: true,
    pressureOpacityEnabled: false,
    isEraser: false,
    scatter: 0,
    rotationJitter: 0,
    usesSmudge: false,
    shapeTextureId: 'hard-round',
  },
  {
    id: 'pencil',
    name: 'Pencil',
    category: 'sketch',
    size: 4,
    minSize: 2,
    maxSize: 20,
    opacity: 0.85,
    spacing: 0.08,
    hardness: 0.9,
    smoothing: 0.3,
    pressureSizeEnabled: true,
    pressureOpacityEnabled: true,
    isEraser: false,
    scatter: 0.02,
    rotationJitter: 5,
    usesSmudge: false,
    shapeTextureId: 'pencil-grain',
    grainTextureId: 'paper-fine',
  },
  {
    id: 'ink',
    name: 'Ink',
    category: 'draw',
    size: 6,
    minSize: 3,
    maxSize: 30,
    opacity: 1,
    spacing: 0.06,
    hardness: 1,
    smoothing: 0.6,
    pressureSizeEnabled: true,
    pressureOpacityEnabled: false,
    isEraser: false,
    scatter: 0,
    rotationJitter: 0,
    usesSmudge: false,
    shapeTextureId: 'ink-splatter',
  },

  // ── Paint ──
  {
    id: 'watercolor',
    name: 'Watercolor',
    category: 'paint',
    size: 40,
    minSize: 20,
    maxSize: 150,
    opacity: 0.15,
    spacing: 0.04,
    hardness: 0.1,
    smoothing: 0.4,
    pressureSizeEnabled: true,
    pressureOpacityEnabled: true,
    isEraser: false,
    scatter: 0.05,
    rotationJitter: 15,
    usesSmudge: false,
    shapeTextureId: 'watercolor-bleed',
    grainTextureId: 'paper-rough',
  },
  {
    id: 'oil',
    name: 'Oil',
    category: 'paint',
    size: 25,
    minSize: 10,
    maxSize: 100,
    opacity: 0.7,
    spacing: 0.08,
    hardness: 0.4,
    smoothing: 0.5,
    pressureSizeEnabled: true,
    pressureOpacityEnabled: true,
    isEraser: false,
    scatter: 0.03,
    rotationJitter: 8,
    usesSmudge: false,
    shapeTextureId: 'oil-bristle',
    grainTextureId: 'canvas-weave',
  },
  {
    id: 'marker',
    name: 'Marker',
    category: 'paint',
    size: 20,
    minSize: 10,
    maxSize: 80,
    opacity: 0.6,
    spacing: 0.06,
    hardness: 0.7,
    smoothing: 0.2,
    pressureSizeEnabled: false,
    pressureOpacityEnabled: false,
    isEraser: false,
    scatter: 0,
    rotationJitter: 0,
    usesSmudge: false,
    shapeTextureId: 'marker-flat',
  },

  // ── Sketch ──
  {
    id: 'pastel',
    name: 'Pastel',
    category: 'sketch',
    size: 30,
    minSize: 15,
    maxSize: 80,
    opacity: 0.5,
    spacing: 0.06,
    hardness: 0.3,
    smoothing: 0.3,
    pressureSizeEnabled: true,
    pressureOpacityEnabled: true,
    isEraser: false,
    scatter: 0.04,
    rotationJitter: 12,
    usesSmudge: false,
    shapeTextureId: 'pastel-rough',
    grainTextureId: 'paper-rough',
  },
  {
    id: 'charcoal',
    name: 'Charcoal',
    category: 'sketch',
    size: 15,
    minSize: 5,
    maxSize: 60,
    opacity: 0.7,
    spacing: 0.07,
    hardness: 0.5,
    smoothing: 0.4,
    pressureSizeEnabled: true,
    pressureOpacityEnabled: true,
    isEraser: false,
    scatter: 0.06,
    rotationJitter: 20,
    usesSmudge: false,
    shapeTextureId: 'charcoal-grain',
    grainTextureId: 'paper-rough',
  },
  {
    id: 'soft-airbrush',
    name: 'Airbrush',
    category: 'paint',
    size: 60,
    minSize: 20,
    maxSize: 200,
    opacity: 0.3,
    spacing: 0.05,
    hardness: 0,
    smoothing: 0.3,
    pressureSizeEnabled: true,
    pressureOpacityEnabled: true,
    isEraser: false,
    scatter: 0,
    rotationJitter: 0,
    usesSmudge: false,
    shapeTextureId: 'airbrush-gradient',
  },
  {
    id: 'flat',
    name: 'Flat',
    category: 'draw',
    size: 20,
    minSize: 5,
    maxSize: 80,
    opacity: 1,
    spacing: 0.08,
    hardness: 0.85,
    smoothing: 0.5,
    pressureSizeEnabled: true,
    pressureOpacityEnabled: false,
    isEraser: false,
    scatter: 0,
    rotationJitter: 0,
    usesSmudge: false,
    shapeTextureId: 'flat-square',
  },

  // ── Blend ──
  {
    id: 'smudge',
    name: 'Smudge',
    category: 'blend',
    size: 30,
    minSize: 20,
    maxSize: 100,
    opacity: 0.5,
    spacing: 0.04,
    hardness: 0.2,
    smoothing: 0.5,
    pressureSizeEnabled: true,
    pressureOpacityEnabled: true,
    isEraser: false,
    scatter: 0,
    rotationJitter: 0,
    usesSmudge: true,
    shapeTextureId: 'smudge-soft',
  },

  // ── Utility ──
  {
    id: 'hard-eraser',
    name: 'Eraser',
    category: 'utility',
    size: 30,
    minSize: 10,
    maxSize: 100,
    opacity: 1,
    spacing: 0.1,
    hardness: 1,
    smoothing: 0.5,
    pressureSizeEnabled: true,
    pressureOpacityEnabled: false,
    isEraser: true,
    scatter: 0,
    rotationJitter: 0,
    usesSmudge: false,
    shapeTextureId: 'hard-round',
  },
]

export const BRUSH_CATEGORIES: { id: BrushCategory; label: string }[] = [
  { id: 'draw', label: 'Draw' },
  { id: 'paint', label: 'Paint' },
  { id: 'sketch', label: 'Sketch' },
  { id: 'blend', label: 'Blend' },
  { id: 'utility', label: 'Utility' },
]

export function getPresetById(id: string): BrushPreset | undefined {
  return DEFAULT_PRESETS.find((p) => p.id === id)
}

export function getPresetsByCategory(category: BrushCategory): BrushPreset[] {
  return DEFAULT_PRESETS.filter((p) => p.category === category)
}
